### PR TITLE
Fix datetime parsing for newer TAK clients that don't include microseconds in the timestamp

### PR DESCRIPTION
**Pull request by brian7704**
This addresses issue #15

### CODE REVIEW

**Comment by sei-jmattson** [comment]
Hey there. I guess I should have checked here first! I just submitted a PR with the same intent.

Although am I missing something? Both your format strings are the same?

**Comment by brian7704** [comment]
Good catch, I must have made a copy/paste error. I'll fix it now.

**Comment by sei-jmattson** [comment]
I added mine with a test included.  If you want to copy that test over, I'll close my PR.
Though we named format string the opposite, I see we both try the "...%SZ" first, which seems like the right call.

**Comment by brian7704** [comment]
Thanks, I added the test to my PR. As for the naming, I really don't know which is which. I tried reading through this document https://www.w3.org/TR/xmlschema-2/#dateTime but it still wasn't really clear. But like you said, we try both so it should work fine.

**Comment by sei-jmattson** [comment]
The difference between the two: 
- W3C_XML_DATETIME requires all time components and optionally allows fractional seconds
- ISO_8601_UTC time components are optional and last time component can be fractional. (i.e. 2024-06-13T16:13.5Z resolves to 16:13:30)

I think for TAK this PR is fine with the assumption that TAK COT messages always use W3C_XML_DATETIME with "Z" for time zone.

So technically the format strings should be named W3C_XML_DATETIME and W3C_XML_DATETIME_FRACTIONAL, or some such.  Unless you want to validate against a regular expression or something.

https://www.w3.org/TR/xmlschema11-2/#dateTime
https://en.wikipedia.org/wiki/ISO_8601#Times

**Comment by ampledata** [comment]
See also #7

**Pull request merged**
